agent:
  name: chat_completion
  description: Agent with a chatbot that makes a call to the LLM model using a context uploaded from a file
templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: { }
- template_name: ImageReader
  class_name: FolderImageDatasetCV2
  template_input: InputTemplate
  attributes:
    load_on_init : True
    data_dir: './artifacts'
    pattern : 'test_img.png'
- template_name: LazyAudioReaderPydub
  class_name: LazyAudioReaderPydub
  template_input: ImageReader
  attributes:
    audio_file_path : none
    source : gradio
    from_bytes : False
- template_name : SpeechToTextTransformers-1
  class_name: 'SpeechToTextTransformers'
  template_input: LazyAudioReaderPydub
  attributes:
    model_path: "openai/whisper-small"
    seed: 1000
    device: "cpu"
    pipeline_kwargs:
      chunk_length_s: 30
    inference_kwargs:
      return_timestamps: word
      generate_kwargs:
        return_segments: True
- template_name: LLaMATextCompletion
  class_name: LLaMATextCompletion
  template_input: SpeechToTextTransformers-1
  attributes:
    llm_model_name: bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF
    llm_model_file: DeepSeek-R1-Distill-Qwen-7B-Q5_K_S.gguf
    n_ctx: 9000
    max_tokens: 10000
    temperature: 0.7
    n_threads: 8
    n_gpu_layers: 29
    chat_format: chatml
    system_prompt : 'You are a helpful assistant'
    keep_before: True
- template_name: ElevenLabsVoiceGeneration
  class_name: ElevenLabsVoiceGeneration
  template_input: LLaMATextCompletion
  attributes:
    voice_description: A warm and engaging Mexican Spanish female voice, perfect for storytelling, audiobooks, and podcasts. Clear and expressive, with a natural, captivating tone, ideal for social media, YouTube, TikTok, and more.
