agent:
  name: chat_completion
  description: Agent with a chatbot that makes a call to the LLM model using a context uploaded from a file
templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: { }
- template_name: PythonLoader-agent
  class_name: PythonLoaderWrapper
  template_input: InputTemplate
  attributes:
    add_document_as_text_packet: 0
    pythonloader_init:
      file_path: .venv/lib/python3.10/site-packages/sinapsis_core/agent/agent.py
- template_name: PythonLoader-template
  class_name: PythonLoaderWrapper
  template_input: PythonLoader-agent
  attributes:
    add_document_as_text_packet: 0
    pythonloader_init:
      file_path: .venv/lib/python3.10/site-packages/sinapsis_core/template_base/template.py
- template_name: TextLoader-config
  class_name: TextLoaderWrapper
  template_input: PythonLoader-template
  attributes:
    add_document_as_text_packet: 0
    textloader_init:
      file_path: .venv/lib/python3.10/site-packages/sinapsis/configs/hello_world_agent.yml
- template_name: LazyAudioReaderPydub
  class_name: LazyAudioReaderPydub
  template_input: TextLoader-config
  attributes:
    audio_file_path : none
    source : gradio
    from_bytes : False
- template_name : SpeechToTextTransformers-1
  class_name: 'SpeechToTextTransformers'
  template_input: LazyAudioReaderPydub
  attributes:
    model_path: "openai/whisper-small"
    seed: 1000
    device: "cpu"
    pipeline_kwargs:
      chunk_length_s: 30
    inference_kwargs:
      return_timestamps: word
      generate_kwargs:
        return_segments: True
- template_name: QueryContextualizerFromFile
  class_name: QueryContextualizeFromFile
  template_input: SpeechToTextTransformers-1
  attributes:
    keywords: [template, agent, config]
    generic_keys: [PythonLoader-agent, PythonLoader-template, TextLoader-config]
- template_name: LLaMATextCompletion
  class_name: LLaMATextCompletion
  template_input: QueryContextualizerFromFile
  attributes:
    llm_model_name: bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF
    llm_model_file: DeepSeek-R1-Distill-Qwen-7B-Q5_K_S.gguf
    n_ctx: 9000
    max_tokens: 10000
    temperature: 0.7
    n_threads: 8
    n_gpu_layers: 29
    chat_format: chatml
    system_prompt : "You are a python and AI agents expert and you provided reasoning behind every answer you give."
    keep_before: False