agent:
  name: chat_completion

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: LazyAudioReaderPydub
  class_name: LazyAudioReaderPydub
  template_input: InputTemplate
  attributes:
    audio_file_path : none
    source : gradio
    from_bytes : False
- template_name : SpeechToTextTransformers-1
  class_name: 'SpeechToTextTransformers'
  template_input: LazyAudioReaderPydub
  attributes:
    model_path: "openai/whisper-small"
    seed: 1000
    device: "cpu"
    pipeline_kwargs:
      chunk_length_s: 30
    inference_kwargs:
      return_timestamps: word
      generate_kwargs:
        return_segments: True

- template_name: QueryContextualizerFromText-template
  class_name: QueryContextualizeFromText
  template_input: SpeechToTextTransformers-1
  attributes:
    keywords: [template, agent, config]

- template_name: LLaMATextCompletion
  class_name: LLaMATextCompletion
  template_input: QueryContextualizerFromText-template
  attributes:
    llm_model_name: bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF
    llm_model_file: DeepSeek-R1-Distill-Qwen-7B-Q5_K_S.gguf
    n_ctx: 9000
    max_tokens: 10000
    temperature: 0.7
    n_threads: 8
    n_gpu_layers: 29
    chat_format: chatml
    system_prompt : "You are a python and AI agents expert and you provided reasoning behind every answer you give."
    keep_before : false