agent:
  name: my_test_agent
  description: Deletes all memories for user 'my_user'

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: Mem0Delete
  class_name: Mem0Delete
  template_input: InputTemplate
  attributes:
    use_managed: true
    memory_config:
      host: null
      org_id: null
      project_id: null
    delete_all: true
    delete_kwargs:
      user_id: my_user