services:
  sinapsis-chatbots: &default
    image: sinapsis-chatbots:base

    build:
      context: ../
      dockerfile: docker/Dockerfile
      ssh:
        - default

    shm_size: '8gb'
    environment:
      PYTHONUNBUFFERED: 1
      GRADIO_SHARE_APP: ${GRADIO_SHARE_APP:-false}
      PYTHONPATH: /lib/python3.10/:/app/.venv/lib/python3.10/site-packages
      LD_LIBRARY_PATH: /app/.venv/lib/python3.10/site-packages/nvidia/cublas/lib
      CUDA_HOME: /usr/local/cuda-12.4
    volumes:
      - "~/.cache/torch:/root/.cache/torch"
      - "~/.cache/huggingface/hub:/root/.cache/huggingface/hub"
      - "~/.cache/sinapsis/:/root/.cache/sinapsis"
    network_mode: 'host'
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
