
FROM sinapsis-nvidia:base
ENV CUDACXX=/usr/local/cuda-12.4/bin/nvcc
ENV CMAKE_ARGS="-DGGML_CUDA=on"
ENV FORCE_CMAKE="1"

RUN apt-get update && apt-get install -y cuda-toolkit-12-4  ninja-build git

COPY . /app/
WORKDIR /app
RUN uv build && uv build --all-packages
RUN uv sync --frozen

RUN uv pip install /app/dist/sinapsis_chatbots_base-0.1.0-py3-none-any.whl[all]
RUN uv pip install /app/dist/sinapsis_llama_cpp-0.2.0-py3-none-any.whl[all]
RUN uv pip install /app/dist/sinapsis_llama_index-0.1.0-py3-none-any.whl[all]
RUN uv pip install /app/dist/sinapsis_qwen-0.1.0-py3-none-any.whl[all]
RUN uv pip install /app/dist/sinapsis_chatbots-0.2.0-py3-none-any.whl[all]
RUN uv pip install numpy==1.26.4
RUN uv pip install flash-attn --no-build-isolation --upgrade
