agent:
  name: my_test_agent
  description: Get memories from Mem0's platform

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: Mem0Get
  class_name: Mem0Get
  template_input: InputTemplate
  attributes:
    use_managed: false
    memory_config:
      vector_store:
        provider: pgvector
        config:
          host: localhost
          port: 5432
          user: postgres
          password: mypass
          dbname: mem0db
          collection_name: mem0_memories
    get_all: true
    get_kwargs:
      user_id: my_user
