agent:
  name: chat_completion
  description: Chatbot using llama-cpp with Mem0 memory integration

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: { }

- template_name: LazyAudioReaderPydub
  class_name: LazyAudioReaderPydub
  template_input: InputTemplate
  attributes:
    audio_file_path : none
    source : gradio
    from_bytes : False

- template_name : SpeechToTextTransformers
  class_name: 'SpeechToTextTransformers'
  template_input: LazyAudioReaderPydub
  attributes:
      model_path: openai/whisper-small
      device: cuda
      pipeline_kwargs:
        chunk_length_s: 30
        return_timestamps : word
        generate_kwargs:
          return_segments : True

- template_name: Mem0Search
  class_name: Mem0Search
  template_input: SpeechToTextTransformers
  attributes:
    use_managed: false
    memory_config:
      vector_store:
        provider: pgvector
        config:
          host: localhost
          port: 5432
          user: postgres
          password: mypass
          dbname: mem0db
          collection_name: mem0_memories
          embedding_model_dims: 384
      llm:
        provider: openai
        config:
          model: gpt-4.1-mini
          temperature: 0.7
          max_tokens: 2000
      embedder:
        provider: huggingface
        config:
          model: Snowflake/snowflake-arctic-embed-xs
          embedding_dims: 384
    enclosure: bracket
    search_kwargs:
      user_id: my_user
      limit: 3
      threshold: 0.1

- template_name: LLaMATextCompletion
  class_name: LLaMATextCompletion
  template_input: Mem0Search
  attributes:
    llm_model_name: bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF
    llm_model_file: DeepSeek-R1-Distill-Qwen-7B-Q5_K_S.gguf
    n_ctx: 9000
    max_tokens: 10000
    temperature: 0.7
    n_threads: 8
    n_gpu_layers: 29
    chat_format: chatml
    system_prompt: 'Answer the question based on query and memories.'
    keep_before: True

- template_name: Mem0Add
  class_name: Mem0Add
  template_input: LLaMATextCompletion
  attributes:
    use_managed: false
    memory_config:
      vector_store:
        provider: pgvector
        config:
          host: localhost
          port: 5432
          user: postgres
          password: mypass
          dbname: mem0db
          collection_name: mem0_memories
          embedding_model_dims: 384
      llm:
        provider: openai
        config:
          model: gpt-4.1-mini
          temperature: 0.7
          max_tokens: 2000
      embedder:
        provider: huggingface
        config:
          model: Snowflake/snowflake-arctic-embed-xs
          embedding_dims: 384
    add_kwargs:
      user_id: my_user
      infer: true
    generic_key: Mem0Search