agent:
  name: chat_completion
  description: Agent with a chatbot that makes a call to the LLM model and preserves history

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: { }

- template_name: TextInput
  class_name: TextInput
  template_input: InputTemplate
  attributes:
    text: "How many states does it have?"
    id: "sinapsis-user"
    source: "1"
- template_name : ChatHistorySaver
  class_name: ChatHistorySaver
  template_input: TextInput
  attributes:
    db_config:
      user: "postgres"
      password: "password"
      host: "localhost"
      port: 5432
      db_name: "test"
      table: "chat_messages2"