agent:
  name: chat_completion
  description: Agent with a chatbot that makes a call to the LLM model and preserves history

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: { }

- template_name: TextInput
  class_name: TextInput
  template_input: InputTemplate
  attributes:
    text: "How many states does it have?"
    id: "Carlos"
    source: "1"

#- template_name : ChatHistoryFetcher
#  class_name: ChatHistoryFetcher
#  template_input: TextInput
#  attributes:
#    db_config:
#      user: "postgres"
#      password: "password"
#      host: "localhost"
#      port: 5432
#      db_name: "test"
#      table: "chat_messages"
#    search_kwargs:
#      limit: 10

#- template_name: LLaMATextCompletion
#  class_name: LLaMATextCompletion
#  template_input: ChatHistoryFetcher
#  attributes:
#    llm_model_name: bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF
#    llm_model_file: DeepSeek-R1-Distill-Qwen-7B-Q5_K_S.gguf
#    n_ctx: 9000
#    max_tokens: 10000
#    temperature: 0.7
#    n_threads: 8
#    n_gpu_layers: 29
#    chat_format: chatml
#    system_prompt : 'You are a helpful assistant'
#    pattern: "</think>"
#    keep_before: False
#    chat_history_key: "ChatHistoryFetcher"

- template_name : ChatHistorySaver
  class_name: ChatHistorySaver
  template_input: TextInput
  attributes:
    db_config:
      user: "postgres"
      password: "password"
      host: "localhost"
      port: 5432
      db_name: "test"
      table: "chat_messages2"