agent:
  name: my_claude_agent
  description: Agent with support for text-to-text and image-to-text conversational chatbots using Anthropic's Claude models
templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: { }
- template_name: ImageReader
  class_name: FolderImageDatasetCV2
  template_input: InputTemplate
  attributes:
    load_on_init : True
    data_dir: './artifacts'
    pattern : 'sunset.jpeg'
- template_name: LazyAudioReaderPydub
  class_name: LazyAudioReaderPydub
  template_input: ImageReader
  attributes:
    audio_file_path : none
    source : gradio
    from_bytes : False
- template_name : SpeechToTextTransformers-1
  class_name: 'SpeechToTextTransformers'
  template_input: LazyAudioReaderPydub
  attributes:
    model_path: "openai/whisper-small"
    seed: 1000
    device: "cpu"
    pipeline_kwargs:
      chunk_length_s: 30
    inference_kwargs:
      return_timestamps: word
      generate_kwargs:
        return_segments: True
- template_name: AnthropicMultiModal
  class_name: AnthropicMultiModal
  template_input: SpeechToTextTransformers-1
  attributes:
    llm_model_name: claude-3-opus-20240229
    max_tokens: 4000
    temperature: 1